version: "3.9"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: laragigs_nginx
        ports:
            - "8081:80"
        volumes:
            - "./src:/var/www/html"
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: laragigs_mysql
        ports:
            - "3306:3306"
        volumes:
            - "./mysql:/var/lib/mysql"
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: laragigs
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            # SERVICE_TAGS: dev
            MYSQL_SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Containerfile
        container_name: laragigs_php
        volumes:
            - "./src:/var/www/html"
        ports:
            - "9000:9000"
        networks:
            - laravel
